//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace SCGESP.Localhost {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ElegrpSoap", Namespace="http://tempuri.org/")]
    public partial class Elegrp : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback PeticionCatalogoOperationCompleted;
        
        private System.Threading.SendOrPostCallback PeticionConsultaOperationCompleted;
        
        private System.Threading.SendOrPostCallback PeticionReporteOperationCompleted;
        
        private System.Threading.SendOrPostCallback PeticionGeneralOperationCompleted;
        
        private System.Threading.SendOrPostCallback FechaActualOperationCompleted;
        
        private System.Threading.SendOrPostCallback UltimoDiaAnioActualOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Elegrp() {
            this.Url = global::SCGESP.Properties.Settings.Default.SCGESP_Localhost_Elegrp;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event PeticionCatalogoCompletedEventHandler PeticionCatalogoCompleted;
        
        /// <remarks/>
        public event PeticionConsultaCompletedEventHandler PeticionConsultaCompleted;
        
        /// <remarks/>
        public event PeticionReporteCompletedEventHandler PeticionReporteCompleted;
        
        /// <remarks/>
        public event PeticionGeneralCompletedEventHandler PeticionGeneralCompleted;
        
        /// <remarks/>
        public event FechaActualCompletedEventHandler FechaActualCompleted;
        
        /// <remarks/>
        public event UltimoDiaAnioActualCompletedEventHandler UltimoDiaAnioActualCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/PeticionCatalogo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("respuesta")]
        public string PeticionCatalogo(System.Xml.XmlNode doc) {
            object[] results = this.Invoke("PeticionCatalogo", new object[] {
                        doc});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void PeticionCatalogoAsync(System.Xml.XmlNode doc) {
            this.PeticionCatalogoAsync(doc, null);
        }
        
        /// <remarks/>
        public void PeticionCatalogoAsync(System.Xml.XmlNode doc, object userState) {
            if ((this.PeticionCatalogoOperationCompleted == null)) {
                this.PeticionCatalogoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPeticionCatalogoOperationCompleted);
            }
            this.InvokeAsync("PeticionCatalogo", new object[] {
                        doc}, this.PeticionCatalogoOperationCompleted, userState);
        }
        
        private void OnPeticionCatalogoOperationCompleted(object arg) {
            if ((this.PeticionCatalogoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PeticionCatalogoCompleted(this, new PeticionCatalogoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/PeticionConsulta", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("respuesta")]
        public string PeticionConsulta(System.Xml.XmlNode doc) {
            object[] results = this.Invoke("PeticionConsulta", new object[] {
                        doc});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void PeticionConsultaAsync(System.Xml.XmlNode doc) {
            this.PeticionConsultaAsync(doc, null);
        }
        
        /// <remarks/>
        public void PeticionConsultaAsync(System.Xml.XmlNode doc, object userState) {
            if ((this.PeticionConsultaOperationCompleted == null)) {
                this.PeticionConsultaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPeticionConsultaOperationCompleted);
            }
            this.InvokeAsync("PeticionConsulta", new object[] {
                        doc}, this.PeticionConsultaOperationCompleted, userState);
        }
        
        private void OnPeticionConsultaOperationCompleted(object arg) {
            if ((this.PeticionConsultaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PeticionConsultaCompleted(this, new PeticionConsultaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/PeticionReporte", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("respuesta")]
        public string PeticionReporte(System.Xml.XmlNode doc) {
            object[] results = this.Invoke("PeticionReporte", new object[] {
                        doc});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void PeticionReporteAsync(System.Xml.XmlNode doc) {
            this.PeticionReporteAsync(doc, null);
        }
        
        /// <remarks/>
        public void PeticionReporteAsync(System.Xml.XmlNode doc, object userState) {
            if ((this.PeticionReporteOperationCompleted == null)) {
                this.PeticionReporteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPeticionReporteOperationCompleted);
            }
            this.InvokeAsync("PeticionReporte", new object[] {
                        doc}, this.PeticionReporteOperationCompleted, userState);
        }
        
        private void OnPeticionReporteOperationCompleted(object arg) {
            if ((this.PeticionReporteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PeticionReporteCompleted(this, new PeticionReporteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/PeticionGeneral", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("respuesta")]
        public string PeticionGeneral(System.Xml.XmlNode doc) {
            object[] results = this.Invoke("PeticionGeneral", new object[] {
                        doc});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void PeticionGeneralAsync(System.Xml.XmlNode doc) {
            this.PeticionGeneralAsync(doc, null);
        }
        
        /// <remarks/>
        public void PeticionGeneralAsync(System.Xml.XmlNode doc, object userState) {
            if ((this.PeticionGeneralOperationCompleted == null)) {
                this.PeticionGeneralOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPeticionGeneralOperationCompleted);
            }
            this.InvokeAsync("PeticionGeneral", new object[] {
                        doc}, this.PeticionGeneralOperationCompleted, userState);
        }
        
        private void OnPeticionGeneralOperationCompleted(object arg) {
            if ((this.PeticionGeneralCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PeticionGeneralCompleted(this, new PeticionGeneralCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/FechaActual", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.DateTime FechaActual() {
            object[] results = this.Invoke("FechaActual", new object[0]);
            return ((System.DateTime)(results[0]));
        }
        
        /// <remarks/>
        public void FechaActualAsync() {
            this.FechaActualAsync(null);
        }
        
        /// <remarks/>
        public void FechaActualAsync(object userState) {
            if ((this.FechaActualOperationCompleted == null)) {
                this.FechaActualOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFechaActualOperationCompleted);
            }
            this.InvokeAsync("FechaActual", new object[0], this.FechaActualOperationCompleted, userState);
        }
        
        private void OnFechaActualOperationCompleted(object arg) {
            if ((this.FechaActualCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.FechaActualCompleted(this, new FechaActualCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UltimoDiaAnioActual", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.DateTime UltimoDiaAnioActual() {
            object[] results = this.Invoke("UltimoDiaAnioActual", new object[0]);
            return ((System.DateTime)(results[0]));
        }
        
        /// <remarks/>
        public void UltimoDiaAnioActualAsync() {
            this.UltimoDiaAnioActualAsync(null);
        }
        
        /// <remarks/>
        public void UltimoDiaAnioActualAsync(object userState) {
            if ((this.UltimoDiaAnioActualOperationCompleted == null)) {
                this.UltimoDiaAnioActualOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUltimoDiaAnioActualOperationCompleted);
            }
            this.InvokeAsync("UltimoDiaAnioActual", new object[0], this.UltimoDiaAnioActualOperationCompleted, userState);
        }
        
        private void OnUltimoDiaAnioActualOperationCompleted(object arg) {
            if ((this.UltimoDiaAnioActualCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UltimoDiaAnioActualCompleted(this, new UltimoDiaAnioActualCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void PeticionCatalogoCompletedEventHandler(object sender, PeticionCatalogoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PeticionCatalogoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PeticionCatalogoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void PeticionConsultaCompletedEventHandler(object sender, PeticionConsultaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PeticionConsultaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PeticionConsultaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void PeticionReporteCompletedEventHandler(object sender, PeticionReporteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PeticionReporteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PeticionReporteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void PeticionGeneralCompletedEventHandler(object sender, PeticionGeneralCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PeticionGeneralCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PeticionGeneralCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void FechaActualCompletedEventHandler(object sender, FechaActualCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FechaActualCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal FechaActualCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.DateTime Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.DateTime)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void UltimoDiaAnioActualCompletedEventHandler(object sender, UltimoDiaAnioActualCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UltimoDiaAnioActualCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UltimoDiaAnioActualCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.DateTime Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.DateTime)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591